/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.preferencia.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.preferencia.logic.dto.PreferenciaDTO;
import co.edu.uniandes.csw.Arquidalgos.preferencia.persistence.api._IPreferenciaPersistence;
import co.edu.uniandes.csw.Arquidalgos.preferencia.persistence.converter.PreferenciaConverter;
import co.edu.uniandes.csw.Arquidalgos.preferencia.persistence.entity.PreferenciaEntity;

public abstract class _PreferenciaPersistence implements _IPreferenciaPersistence {

  	@PersistenceContext(unitName="TuMeOpPU")
 
	protected EntityManager entityManager;
	
	public PreferenciaDTO createPreferencia(PreferenciaDTO preferencia) {
		PreferenciaEntity entity=PreferenciaConverter.persistenceDTO2Entity(preferencia);
		entityManager.persist(entity);
		return PreferenciaConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<PreferenciaDTO> getPreferencias() {
		Query q = entityManager.createQuery("select u from PreferenciaEntity u");
		return PreferenciaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public PreferenciaDTO getPreferencia(Long id) {
		return PreferenciaConverter.entity2PersistenceDTO(entityManager.find(PreferenciaEntity.class, id));
	}

	public void deletePreferencia(Long id) {
		PreferenciaEntity entity=entityManager.find(PreferenciaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePreferencia(PreferenciaDTO detail) {
		PreferenciaEntity entity=entityManager.merge(PreferenciaConverter.persistenceDTO2Entity(detail));
		PreferenciaConverter.entity2PersistenceDTO(entity);
	}

}