/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.tienda.service;

import co.edu.uniandes.csw.Arquidalgos.tienda.logic.api.ITiendaLogicService;
import co.edu.uniandes.csw.Arquidalgos.tienda.logic.dto.TiendaDTO;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;


public abstract class _TiendaService {

	@Inject
	protected ITiendaLogicService tiendaLogicService;
	
	@POST
	public List<TiendaDTO> createTienda(List<TiendaDTO> tiendaL){
            List<TiendaDTO> lista = getTiendas();
            List<TiendaDTO> resp = new ArrayList<TiendaDTO>();
            for (int i = 0; i < tiendaL.size(); i++) {
                TiendaDTO tiendaAct = tiendaL.get(i);
                String idnuevo = tiendaAct.getFacebookId();
                boolean encontrado = false;
                for (int j = 0; j < lista.size(); j++) {
                    if(lista.get(j).getFacebookId().equals(idnuevo))
                    {
                        encontrado=true;
                    }
                }
                if(!encontrado)
                {
		tiendaLogicService.createTienda(tiendaAct);
                }
            }
            return resp;
	}
	
	@DELETE
	@Path("{id}")
	public void deleteTienda(@PathParam("id") Long id){
		tiendaLogicService.deleteTienda(id);
	}
	
	@GET
	public List<TiendaDTO> getTiendas(){
		return tiendaLogicService.getTiendas();
	}
	
	@GET
	@Path("{id}")
	public TiendaDTO getTienda(@PathParam("id") Long id){
		return tiendaLogicService.getTienda(id);
	}
	
	@PUT
    @Path("{id}")
	public void updateTienda(@PathParam("id") Long id, TiendaDTO tienda){
		tiendaLogicService.updateTienda(tienda);
	}
	
}