/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.preferencia.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.Arquidalgos.preferencia.logic.dto.PreferenciaDTO;
import co.edu.uniandes.csw.Arquidalgos.preferencia.persistence.entity.PreferenciaEntity;

public abstract class _PreferenciaConverter {

	public static PreferenciaDTO entity2PersistenceDTO(PreferenciaEntity entity){
		if (entity != null) {
			PreferenciaDTO dto = new PreferenciaDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setNumeroDeComentarios(entity.getNumeroDeComentarios());
					dto.setMeGusta(entity.getMeGusta());
					dto.setTienda_preId(entity.getTienda_preId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static PreferenciaEntity persistenceDTO2Entity(PreferenciaDTO dto){
		if(dto!=null){
			PreferenciaEntity entity=new PreferenciaEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setNumeroDeComentarios(dto.getNumeroDeComentarios());
			
					entity.setMeGusta(dto.getMeGusta());
			
					entity.setTienda_preId(dto.getTienda_preId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<PreferenciaDTO> entity2PersistenceDTOList(List<PreferenciaEntity> entities){
		List<PreferenciaDTO> dtos=new ArrayList<PreferenciaDTO>();
		for(PreferenciaEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<PreferenciaEntity> persistenceDTO2EntityList(List<PreferenciaDTO> dtos){
		List<PreferenciaEntity> entities=new ArrayList<PreferenciaEntity>();
		for(PreferenciaDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}