/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.tumeop.master.persistence.entity;

import co.edu.uniandes.csw.Arquidalgos.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.Arquidalgos.tumeop.persistence.entity.TuMeOpEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(TuMeOpusuariosOpEntityId.class)
@NamedQueries({
    @NamedQuery(name = "TuMeOpusuariosOpEntity.getByMasterId", query = "SELECT  u FROM TuMeOpusuariosOpEntity u WHERE u.tuMeOpId=:tuMeOpId"),
    @NamedQuery(name = "TuMeOpusuariosOpEntity.deleteTuMeOpusuariosOpEntity", query = "DELETE FROM TuMeOpusuariosOpEntity u WHERE u.tuMeOpId=:tuMeOpId and  u.usuariosOpId=:usuariosOpId")
})
public class TuMeOpusuariosOpEntity implements Serializable {

    @Id
    @Column(name = "tuMeOpId")
    private Long tuMeOpId;
    @Id
    @Column(name = "usuariosOpId")
    private Long usuariosOpId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tuMeOpId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity tuMeOpIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuariosOpId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuariosOpIdEntity; 

    public TuMeOpusuariosOpEntity() {
    }

    public TuMeOpusuariosOpEntity(Long tuMeOpId, Long usuariosOpId) {
        this.tuMeOpId =tuMeOpId;
        this.usuariosOpId = usuariosOpId;
    }

    public Long getTuMeOpId() {
        return tuMeOpId;
    }

    public void setTuMeOpId(Long tuMeOpId) {
        this.tuMeOpId = tuMeOpId;
    }

    public Long getUsuariosOpId() {
        return usuariosOpId;
    }

    public void setUsuariosOpId(Long usuariosOpId) {
        this.usuariosOpId = usuariosOpId;
    }

    public UsuarioEntity getTuMeOpIdEntity() {
        return tuMeOpIdEntity;
    }

    public void setTuMeOpIdEntity(UsuarioEntity tuMeOpIdEntity) {
        this.tuMeOpIdEntity = tuMeOpIdEntity;
    }

    public UsuarioEntity getUsuariosOpIdEntity() {
        return usuariosOpIdEntity;
    }

    public void setUsuariosOpIdEntity(UsuarioEntity usuariosOpIdEntity) {
        this.usuariosOpIdEntity = usuariosOpIdEntity;
    }

}
