/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.tumeop.master.persistence;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.master.persistence.entity.TuMeOpusuariosOpEntity;
import co.edu.uniandes.csw.Arquidalgos.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.Arquidalgos.tienda.logic.dto.TiendaDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.master.persistence.entity.TuMeOptiendaOPEntity;
import co.edu.uniandes.csw.Arquidalgos.tienda.persistence.converter.TiendaConverter;
import co.edu.uniandes.csw.Arquidalgos.tumeop.logic.dto.TuMeOpDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.master.logic.dto.TuMeOpMasterDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.master.persistence.api._ITuMeOpMasterPersistence;
import co.edu.uniandes.csw.Arquidalgos.tumeop.persistence.api.ITuMeOpPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _TuMeOpMasterPersistence implements _ITuMeOpMasterPersistence {

  	@PersistenceContext(unitName="TuMeOpPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ITuMeOpPersistence tumeopPersistence;  

    public TuMeOpMasterDTO getTuMeOp(Long tumeopId) {
        TuMeOpMasterDTO tumeopMasterDTO = new TuMeOpMasterDTO();
        TuMeOpDTO tumeop = tumeopPersistence.getTuMeOp(tumeopId);
        tumeopMasterDTO.setTuMeOpEntity(tumeop);
        tumeopMasterDTO.setListusuariosOp(getTuMeOpusuariosOpEntityList(tumeopId));
        tumeopMasterDTO.setListtiendaOP(getTuMeOptiendaOPEntityList(tumeopId));
        return tumeopMasterDTO;
    }

    public TuMeOpusuariosOpEntity createTuMeOpusuariosOpEntity(TuMeOpusuariosOpEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteTuMeOpusuariosOpEntity(Long tuMeOpId, Long usuariosOpId) {
        Query q = entityManager.createNamedQuery("TuMeOpusuariosOpEntity.deleteTuMeOpusuariosOpEntity");
        q.setParameter("tuMeOpId", tuMeOpId);
        q.setParameter("usuariosOpId", usuariosOpId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getTuMeOpusuariosOpEntityList(Long tuMeOpId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("TuMeOpusuariosOpEntity.getByMasterId");
        q.setParameter("tuMeOpId",tuMeOpId);
        List<TuMeOpusuariosOpEntity> qResult =  q.getResultList();
        for (TuMeOpusuariosOpEntity entity : qResult) { 
            if(entity.getUsuariosOpIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuariosOpIdEntity()));
        }
        return resp;
    }
    public TuMeOptiendaOPEntity createTuMeOptiendaOPEntity(TuMeOptiendaOPEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteTuMeOptiendaOPEntity(Long tuMeOpId, Long tiendaOPId) {
        Query q = entityManager.createNamedQuery("TuMeOptiendaOPEntity.deleteTuMeOptiendaOPEntity");
        q.setParameter("tuMeOpId", tuMeOpId);
        q.setParameter("tiendaOPId", tiendaOPId);
        q.executeUpdate();
    }

    public List<TiendaDTO> getTuMeOptiendaOPEntityList(Long tuMeOpId) {
        ArrayList<TiendaDTO> resp = new ArrayList<TiendaDTO>();
        Query q = entityManager.createNamedQuery("TuMeOptiendaOPEntity.getByMasterId");
        q.setParameter("tuMeOpId",tuMeOpId);
        List<TuMeOptiendaOPEntity> qResult =  q.getResultList();
        for (TuMeOptiendaOPEntity entity : qResult) { 
            if(entity.getTiendaOPIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TiendaConverter.entity2PersistenceDTO(entity.getTiendaOPIdEntity()));
        }
        return resp;
    }

}
