/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.bono.persistence.entity;

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class _BonoEntity {

	@Id
	@GeneratedValue(generator = "Bono")
	private Long id;
	private String name;
	@Temporal(TemporalType.DATE)
	private Date fecha;
	private Integer valor;
	private Long usuariobnId;
	private Long tienda_bonoId;
        private String tiendafId;

    public String getTiendafId() {
        return tiendafId;
    }

    public void setTiendafId(String tiendafId) {
        this.tiendafId = tiendafId;
    }
        
	public Long getId(){
		return id;
	}
	
	public void setId(Long id){
		this.id = id;
	}
	public String getName(){
		return name;
	}
	
	public void setName(String name){
		this.name = name;
	}
	public Date getFecha(){
		return fecha;
	}
	
	public void setFecha(Date fecha){
		this.fecha = fecha;
	}
	public Integer getValor(){
		return valor;
	}
	
	public void setValor(Integer valor){
		this.valor = valor;
	}
	public Long getUsuariobnId(){
		return usuariobnId;
	}
	
	public void setUsuariobnId(Long usuariobnId){
		this.usuariobnId = usuariobnId;
	}
	public Long getTienda_bonoId(){
		return tienda_bonoId;
	}
	
	public void setTienda_bonoId(Long tienda_bonoId){
		this.tienda_bonoId = tienda_bonoId;
	}
}