/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.tumeop.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.tumeop.logic.dto.TuMeOpDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.persistence.api._ITuMeOpPersistence;
import co.edu.uniandes.csw.Arquidalgos.tumeop.persistence.converter.TuMeOpConverter;
import co.edu.uniandes.csw.Arquidalgos.tumeop.persistence.entity.TuMeOpEntity;

public abstract class _TuMeOpPersistence implements _ITuMeOpPersistence {

  	@PersistenceContext(unitName="TuMeOpPU")
 
	protected EntityManager entityManager;
	
	public TuMeOpDTO createTuMeOp(TuMeOpDTO tuMeOp) {
		TuMeOpEntity entity=TuMeOpConverter.persistenceDTO2Entity(tuMeOp);
		entityManager.persist(entity);
		return TuMeOpConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<TuMeOpDTO> getTuMeOps() {
		Query q = entityManager.createQuery("select u from TuMeOpEntity u");
		return TuMeOpConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public TuMeOpDTO getTuMeOp(Long id) {
		return TuMeOpConverter.entity2PersistenceDTO(entityManager.find(TuMeOpEntity.class, id));
	}

	public void deleteTuMeOp(Long id) {
		TuMeOpEntity entity=entityManager.find(TuMeOpEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateTuMeOp(TuMeOpDTO detail) {
		TuMeOpEntity entity=entityManager.merge(TuMeOpConverter.persistenceDTO2Entity(detail));
		TuMeOpConverter.entity2PersistenceDTO(entity);
	}

}