/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.tumeop.master.logic.dto;

import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.Arquidalgos.tienda.logic.dto.TiendaDTO;
import co.edu.uniandes.csw.Arquidalgos.tumeop.logic.dto.TuMeOpDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _TuMeOpMasterDTO {

 
    protected TuMeOpDTO tumeopEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public TuMeOpDTO getTuMeOpEntity() {
        return tumeopEntity;
    }

    public void setTuMeOpEntity(TuMeOpDTO tumeopEntity) {
        this.tumeopEntity = tumeopEntity;
    }
    
    public List<UsuarioDTO> createusuariosOp;
    public List<UsuarioDTO> updateusuariosOp;
    public List<UsuarioDTO> deleteusuariosOp;
    public List<UsuarioDTO> listusuariosOp;	
    public List<TiendaDTO> createtiendaOP;
    public List<TiendaDTO> updatetiendaOP;
    public List<TiendaDTO> deletetiendaOP;
    public List<TiendaDTO> listtiendaOP;	
	
	
	
    public List<UsuarioDTO> getCreateusuariosOp(){ return createusuariosOp; };
    public void setCreateusuariosOp(List<UsuarioDTO> createusuariosOp){ this.createusuariosOp=createusuariosOp; };
    public List<UsuarioDTO> getUpdateusuariosOp(){ return updateusuariosOp; };
    public void setUpdateusuariosOp(List<UsuarioDTO> updateusuariosOp){ this.updateusuariosOp=updateusuariosOp; };
    public List<UsuarioDTO> getDeleteusuariosOp(){ return deleteusuariosOp; };
    public void setDeleteusuariosOp(List<UsuarioDTO> deleteusuariosOp){ this.deleteusuariosOp=deleteusuariosOp; };
    public List<UsuarioDTO> getListusuariosOp(){ return listusuariosOp; };
    public void setListusuariosOp(List<UsuarioDTO> listusuariosOp){ this.listusuariosOp=listusuariosOp; };	
    public List<TiendaDTO> getCreatetiendaOP(){ return createtiendaOP; };
    public void setCreatetiendaOP(List<TiendaDTO> createtiendaOP){ this.createtiendaOP=createtiendaOP; };
    public List<TiendaDTO> getUpdatetiendaOP(){ return updatetiendaOP; };
    public void setUpdatetiendaOP(List<TiendaDTO> updatetiendaOP){ this.updatetiendaOP=updatetiendaOP; };
    public List<TiendaDTO> getDeletetiendaOP(){ return deletetiendaOP; };
    public void setDeletetiendaOP(List<TiendaDTO> deletetiendaOP){ this.deletetiendaOP=deletetiendaOP; };
    public List<TiendaDTO> getListtiendaOP(){ return listtiendaOP; };
    public void setListtiendaOP(List<TiendaDTO> listtiendaOP){ this.listtiendaOP=listtiendaOP; };	
	
	
}

