/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.usuario.logic.ejb;

import javax.ejb.EJB;
import javax.ejb.LocalBean;
import javax.ejb.Stateless; 
import javax.inject.Inject;

import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.Arquidalgos.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import java.util.List;

@Default
@Stateless
@LocalBean
public class UsuarioLogicService extends _UsuarioLogicService implements IUsuarioLogicService {

    public UsuarioDTO loginUsuario(UsuarioDTO usuario) throws Exception{
        UsuarioDTO prueba = new UsuarioDTO();
        prueba.setEmail("a");
        prueba.setContrasena("a");
        prueba.setName("a");
        createUsuario(prueba);
        
        UsuarioDTO usuarioActual = searchClienteByEmail(usuario);
        if ( usuarioActual == null)
        {
            throw new Exception("El usuario: "+usuario.getEmail()+" con contraseña :"+usuario.getContrasena()
                    +"no existe");
        }
        else if ( usuarioActual.getContrasena().equals(usuario.getContrasena()))
        {
            return usuarioActual;
        }
        else
        {
            throw new Exception("Clave incorrecta. Intente de nuevo");
        }
    }
    
    

}